baseURL = "http://kubernetesbyexample.com"
DefaultContentLanguage = "en"
title = "Openshift By Example"
theme = "beautifulhugo"
metaDataFormat = "yaml"
googleAnalytics = ""

[Params]
  subtitle = "Brought to you by the Red Hat Italy team"
  logo = "img/obe-logo.png"
  favicon = "img/obe-logo.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = false

[Author]
  name = "Red Hat Italy team"
  github = "redhat-italy"
  twitter = "RedHatItaly"

[[menu.main]]
  name = "Try out!"
  url = "diy/"

[[menu.main]]
  name = "Contribute"
  url = "https://github.com/redhat-italy/obe"
