apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 1
  selector:
    app: myhello
  template:
    metadata:
      name: myhello
      labels:
        app: myhello
    spec:
      containers:
      - name: myhello
        image: openshift/hello-openshift:latest
        ports:
        - containerPort: 8080
