apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 1
  selector:
    app: myhello
  template:
    metadata:
      name: myrc
      labels:
        app: myhello
    spec:
      containers:
      - name: myhello
        image: openshift/hello-openshift:latest
        ports:
        - containerPort: 8080
      - name: shell
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "sleep 10000"
