apiVersion: v1
kind: Pod
metadata:
  name: pod2labels
  labels:
    env: production
    owner: giuseppe
spec:
  containers:
  - name: myhello
    image: openshift/hello-openshift:latest
    ports:
    - containerPort: 8080
