apiVersion: v1
kind: Pod
metadata:
  name: podlabeled
  labels:
    env: development
spec:
  containers:
  - name: myhello
    image: openshift/hello-openshift:latest
    ports:
    - containerPort: 8080 
