apiVersion: v1
kind: Pod
metadata:
  name: podWithLabel
  labels:
    env: development
spec:
  containers:
  - name: myhello
    image: openshift/hello-openshift:latest
    ports:
    - containerPort: 8080
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
